version: '3.8'

services:
  frontend:
    image: example-frontend
    ports:
      - "5000:5000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    depends_on:
      - backend
  backend:
    image: example-backend
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
    ports:
      - "8080:8080"
